### ISSUE TITLE
pip install -r requirements.txt gives error message

### ISSUE THREAD

**Issue by librarytechservices** [CS-4820-Library-Project/COUNTER-5-Report-Tool#226]
I am trying to install the C5 Report Tool (disclaimer: this is all very new to me). 

When I enter pip install -r requirements.txt

 I get the following error message:

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Any tips?

**Comment by sesan07** [comment]
Hello! Make sure you're in the project's directory before running the command.

**Comment by librarytechservices** [comment]
It worked. Thank you!

Carine Mattix

From: Samuel Esan ***@***.***>
Sent: Friday, April 2, 2021 1:12 PM
To: CS-4820-Library-Project/COUNTER-5-Report-Tool ***@***.***>
Cc: Carine Mattix ***@***.***>; Author ***@***.***>
Subject: [External] Re: [CS-4820-Library-Project/COUNTER-5-Report-Tool] pip install -r requirements.txt gives error message (#226)


Hello! Make sure you're in the project's directory before running the command.
