### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by reeset** [CS-4820-Library-Project/COUNTER-5-Report-Tool#228]
To determine the project license, I kind of had to go digging in the wiki.  It would be ideal if the license made its way into the code repo and if not present already -- was made clear as part of any install/first run.  Individuals at most public orgs cannot agree to licenses on behalf of their institution -- so license information really needs to be more clear.

**Comment by mbelvadi** [comment]
Thanks for this suggestion. I've put it near the top of the readme.md file, so it's now very visible right on the "home page" of the project here in Github.
